### ISSUE TITLE
Setup AMS, the version variable is defined as 'AMORO_VERSION', but setup use 'AMORO-VERSION'

### ISSUE THREAD

**Issue by wandongchen** [apache/amoro-site#28]
# Rplace version value with the latest Amoro version if needed
export AMORO_VERSION=0.6.0

# Download the binary package of AMS
wget https://github.com/NetEase/amoro/releases/download/v${AMORO_VERSION}/amoro-${AMORO_VERSION}-bin.zip

# Unzip the pakage
unzip amoro-${AMORO-VERSION}-bin.zip

# Start AMS by script
cd amoro-${AMORO-VERSION} && ./bin/ams.sh start

**Comment by zhoujinsong** [comment]
Completed by #29
